version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - govuk-pay
  - javascript
  allow:
  - dependency-name: "@govuk-pay/pay-js-commons"
  - dependency-name: "@govuk-pay/pay-js-metrics"
  ignore:
  - dependency-name: change-case
    versions:
    - ">= 4.a"
    - "< 5"
  - dependency-name: joi
    versions:
    - ">= 17.a"
    - "< 18"
  - dependency-name: "@sentry/node"
    versions:
    - "> 6.12.0"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - govuk-pay
  - docker
  ignore:
  - dependency-name: node
    versions:
    - ">= 23"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 0
  labels:
  - dependencies
  - govuk-pay
  - github_actions
