const CORRELATION_HEADER = process.env.CORRELATION_HEADER_NAME || 'x-request-id'
const PRODUCTS_URL = process.env.PRODUCTS_URL
const PUBLIC_AUTH_URL = process.env.PUBLIC_AUTH_URL

export { CORRELATION_HEADER, PRODUCTS_URL, PUBLIC_AUTH_URL }
