module.exports.enforceLiveAccountOnly = require('./enforce-live-account-only.middleware')
module.exports.simplifiedAccountOptIn = require('./simplified-account-opt-in.middleware')
module.exports.simplifiedAccountStrategy = require('./simplified-account-strategy.middleware')
module.exports.enforcePaymentProviderType = require('./enforce-payment-provider-type.middleware')
module.exports.enforceEmailCollectionModeNotOff = require('./enforce-email-collection-mode-not-off.middleware')
module.exports.checkTaskCompletion = require('./check-task-completion.middleware')
module.exports.defaultViewDecider = require('./settings/default-view-decider.middleware')
