name: Github Actions for NodeJS apps - run cypress tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    name: Cypress tests

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - name: Parse Node version
        id: parse-node-version
        run: echo "node-version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      - name: Setup
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381
        with:
          node-version: ${{ steps.parse-node-version.outputs.node-version }}
      - name: Cache build directories
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: |
            node_modules
            govuk_modules
            public
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}
      - name: Parse Cypress version
        id: parse-cypress-version
        run: echo "CYPRESS_VERSION=$(jq -r '.devDependencies.cypress' package.json)" >> $GITHUB_OUTPUT
      - name: Cache Cypress
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ steps.parse-cypress-version.outputs.CYPRESS_VERSION }}
      - name: Run cypress tests
        run: |
          npm run cypress:server > /dev/null 2>&1 &
          sleep 3
          npm run cypress:test
