name: Github Actions for NodeJS apps - Install and Compile

on:
  workflow_call:
    inputs:
      has_cypress_tests:
        type: boolean
        required: false
        default: false
        description: Set to `true` if app has cypress tests

permissions:
  contents: read

jobs:
  install-and-compile:
    runs-on: ubuntu-latest
    name: Install and compile

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - name: Parse Node version
        id: parse-node-version
        run: echo "node-version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      - name: Setup
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: ${{ steps.parse-node-version.outputs.node-version }}
      - name: Cache build directories
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: |
            node_modules
            govuk_modules
            public
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}
      - name: Cache NPM packages
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Parse Cypress version
        if: ${{ inputs.has_cypress_tests }}
        id: parse-cypress-version
        run: echo "CYPRESS_VERSION=$(jq -r '.devDependencies.cypress' package.json)" >> $GITHUB_OUTPUT
      - name: Cache Cypress
        if: ${{ inputs.has_cypress_tests }}
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ steps.parse-cypress-version.outputs.CYPRESS_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Compile
        run: npm run compile
      - name: Run lint
        run: npm run lint
